---
output:
  md_document:
    variant: markdown_github
---

### linux 

This is a simplified procedure for installing R and R-studio on Ubuntu 16.04 without the use of the commandline. 

- Use Ubuntu Software Center to install Synaptic Package Manager (requires root previlage).  

- Open Synaptic Package Manager and search for r-base. 

- Click on r-base and select Mark for Installation. 

- Click on Apply. (R and its dependencies should be installed.) 

- I found you also need to install libcurl3 package. Search and install libcurl3 using Synaptic Package Manager. 

- Download RStudio by going to [R Studio Download Page](https://www.rstudio.com/products/rstudio/download3/) and selecting 0.99.903 - Ubuntu 12.04+/Debian 8+ (64-bit)  

- Right click the downloaded file for RStudio and select Open With Software Install. Then select install. 

- [Help if you need it](https://www.datascienceriot.com/how-to-install-r-in-linux-ubuntu-16-04-xenial-xerus/kris/) 



### shortcuts on the desktop

RStudio is an integrated development environment (IDE) for R, so I rarely run R directly. For this reason, I suggest

-   Put a shortcut to RStudio on the desktop 

-   Delete the shortcuts to R (if any) on your desktop  






