---
output:
  md_document:
    variant: markdown_github
---



### set up an R project 

- Login with your usual user name. 

- For the new project---for example, an article, a workshop, a course, or a contract, whatever you wish to define as a "project"---create a new folder in your preferred directory. 

- Open RStudio. File menu > New Project > Existing Directory. Use the Browse button to find the folder you just created, then Select > Create Project. 



### create an .Renviron file 

These steps allow you to install future versions of R without having to reinstall all the packages you use. 

Windows users (I do not know if these steps are necessary for Mac and Linux users)

- Create a new directory C:/R/library 
- In RStudio, File menu > New File >  Text File 
- In the text file, type `R_LIBS_USER="C:/R/library"` 
- Save As... to your project root directory, using the filename .Renviron 



### for new RStudio projects 

- Whenever you create a new RStudio Project, paste a copy of the .Renviron file in the project root directory. 



### testing your installation

- Close RStudio 

- Open RStudio. No error statements should appear (we hope). 

- If the course project is open, File > Close Project. No errors? 

- If the course project is closed, open it with File > Open Project. No
errors? 

- Now let's see if the library path you made works. The RStudio interface is divided into 4 window panes. In the lower right pane, select Packages > Install

- In the dialog box that appears, the Install to Library strip should indicate `C:/R/library [Default]`. 

- In the Packages entry box, type plyr and click Install. If all goes well, you'll see something like this in the lower left pane (the R Console). 

```{r echo=TRUE, eval=FALSE}
Installing package into "C:/R/library" (as "lib" is unspecified)
trying URL "http://ftp.ussg.iu.edu/CRAN/bin/windows/contrib/3.1/plyr_1.8.1.zip"
Content type "application/zip" length 1149242 bytes (1.1 Mb)
opened URL
downloaded 1.1 Mb

package "plyr" successfully unpacked and MD5 sums checked

>
```



